# Generated by Django 4.2.7 on 2023-12-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='group',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
