# Generated by Django 4.2.7 on 2024-01-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_remove_customuser_group_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancies',
            name='level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobvacancies',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
