# Generated by Django 4.2.7 on 2024-01-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_companyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
