# Generated by Django 4.2.7 on 2024-01-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_companyreview_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationjobs',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
